version: '2.1'

networks:
  internal_network:
  external_network:

services:
  db: 
    image: mariadb:10.6
    container_name: nextcloud_db
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    networks:
      - internal_network
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    cpus: "0.5"
    mem_limit: 300M

  app:
    image: nextcloud
    container_name: nextcloud_app
    restart: always
    ports:
      - 8080:80
    networks:
      - internal_network
      - external_network
    volumes:
      - ./nextcloud:/var/www/html
    environment:
      - MYSQL_PASSWORD=admin
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=admin
    depends_on:
      - db
    cpus: "1"
    mem_limit: 900M
    
  locust:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: locust
    ports:
      - 8888:8888
    volumes:
      - ./locust:/locust
    command: -f /locust/locustfile.py --host=http://nextcloud_app
    environment:
      - LOCUST_WEB_PORT=8888
    networks:
      - external_network
    cpus: "0.5"
    mem_limit: 500M
    depends_on:
      - app